import os
# print(dir(os))
# print(os.getcwd())
# os.chdir("C://")
# os.chdir('C://AMD')
# print(os.getcwd())
# f=open("rushabh.txt")
# print(os.listdir())
# print(os.listdir("G://"))
# os.mkdir("rushabh") #make a dairectri
# os.mkdir('babbu')
# os.rmdir("babbu")
# os.rmdir("rushabh")
# print(os.listdir('c://'))
# print(os.listdir())
# os.makedirs('babbu/khatu')
# print(os.makedirs("rushabh/prajapati")) #make directri in directri 
# os.rmdir("rushabh/khatu")
# os.rename("RUSHBAH.txt","rushabh.txt")
# print(os.path.exists("C://vscode"))
# print(os.path.exists("G://java"))
# print(os.path.exists("C://VsCode"))
# print(os.path.exists("G://python//game.py"))
# print(os.path.join("c://","/rushabh")) # make a path
# print(os.path.isdir("C://AMD"))
# print(os.path.isdir("G://js")) 
# print(os.path.isdir("rushabh"))
# print(os.path.isfile("G://python//game.py"))
# print(os.path.isfile("game.py"))